services:
  server:
    image: golang:1.25.1
    working_dir: /app
    command: go run ./cmd
    volumes:
      - .:/app:delegated
    ports:
      - "8080:8080"
    environment:
      - GO111MODULE=on
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health-check"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  app-net:
    driver: bridge

